---
title: "Surprise Index"
author: "Tamara Cooper"
date: "2023-07-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, eval=FALSE, echo=FALSE}
# packages
install.packages("rmarkdown");   
install.packages("tidyverse");
install.packages("ggplot2");
install.packages("RColorBrewer");
install.packages("kableExtra");
install.packages("papeR");
install.packages("epitab");
install.packages("gplots");
install.packages("scales")
install.packages("sfsmisc")
```

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(RColorBrewer)
library(MASS)
library(knitr)
library(kableExtra)
library(RColorBrewer)
library("papeR")
library(epitab)
library("gplots")
myPalette <- brewer.pal(8, "Set2"); 
library(dplyr)
library(readxl)
library(stringr)
library("scales")
library(sfsmisc)

options(scipen=10)
```



```{r}
### Binomial distribution
n <- 10
m <- c(1, 3, 5, 8, 10)
SI_0.01 <- c(9.04, 7387.44, 34478242.41, 1.87344*10^(14), 8.26*10^(19))
SI_0.25 <- c(1.09, 0.82, 3.52, 531.61, 215301.13)
SI_0.8 <- c(54639.75, 284.58, 8.47, 0.74, 2.08)

df_SI <- tibble(m, SI_0.01, SI_0.25, SI_0.8)
colnames(df_SI)[c(2:4)] = c("p = 0.01", "p = 0.25", "p = 0.8")
df_SI

dfSurprise <- df_SI %>% pivot_longer(cols = starts_with("p ="), names_to = "prob")

binomPlot <- ggplot(dfSurprise, aes(x = m, y = value, col=prob, group=prob)) + 
  geom_line() + 
  geom_point(aes(shape=prob, col=prob)) +
  scale_y_continuous(trans = 'log10', labels=trans_format('log10',math_format(10^.x))) + scale_x_continuous(limits = c(0.5, 10.5)) + 
  ylab("log(SI)") + 
  theme(legend.title = element_blank()) 

##+ ggtitle("Surprise index values for binomial distribution, n = 10") + theme(plot.title = element_text(hjust = 0.5))
  
binomPlot
```


```{r}
### Negative Binomial distribution
n <- 10
r <- c(1, 3, 5, 8, 10)
SI_0.01 <- c(0.55, 5616123374.28, 1.15*10^(21), 2.98*10^(39), 9.32*10^(52))
SI_0.25 <- c(7.61, 185.21, 88714.07, 2.63*10^(10), 1.93*10^(15))
SI_0.5 <- c(341.33, 61.81, 203.05, 34684.81, 17668300.52)

df_SI <- tibble(r, SI_0.01, SI_0.25, SI_0.5)
colnames(df_SI)[c(2:4)] = c("p = 0.01", "p = 0.25", "p = 0.5")
# df_SI

dfSurprise <- df_SI %>% pivot_longer(cols = starts_with("p ="), names_to = "prob")

negBinomPlot <- ggplot(dfSurprise, aes(x = r, y = value, col=prob, group=prob)) + 
  geom_line() + 
  geom_point(aes(shape=prob, col=prob)) +
  scale_y_continuous(trans = 'log10', labels=trans_format('log10',math_format(10^.x))) + scale_x_continuous(limits = c(0.5, 10.5)) + 
  ylab("log(SI)") + 
  theme(legend.title = element_blank()) 

#+  ggtitle("Surprise index values for negative binomial distribution, n = 10") + theme(plot.title = element_text(hjust = 0.5))
  
negBinomPlot
```


```{r}
### Poisson distribution
n <- 10
m <- c(1, 3, 5, 8, 10)
SI_0.5 <- c(1.54, 36.86, 2948.77, 7926282.59, 2853461732.66)
SI_1 <- c(0.84, 5.03, 100.63, 33812.86, 3043157.28)
SI_2.5 <- c(0.89, 0.86, 2.75, 59.08, 850.81)

df_SI <- tibble(m, SI_0.5, SI_1, SI_2.5)
colnames(df_SI)[c(2:4)] = c("lambda = 0.5", "lambda = 1", "lambda = 2.5")
df_SI

dfSurprise <- df_SI %>% pivot_longer(cols = starts_with("lambda ="), names_to = "lambda")

poisPlot <- ggplot(dfSurprise, aes(x = m, y = value, col=lambda, group=lambda)) + 
  geom_line() + 
  geom_point(aes(shape=lambda, col=lambda)) +
  scale_y_continuous(trans = 'log10', labels = scales::comma) + scale_x_continuous(limits = c(0.5, 10.5)) + 
  ylab("log(SI)") + 
  theme(legend.title = element_blank()) 

#+ ggtitle("Surprise index values for Poisson distribution") + theme(plot.title = element_text(hjust = 0.5))
  
poisPlot
```


```{r}
### zero-truncated Poisson distribution
n <- 10
m <- c(1, 3, 5, 8, 10)
SI_0.5 <- c(0.79, 19.05, 1523.94, 4096347.51, 1474685102.05)
SI_1 <- c(0.69, 4.14, 82.89, 27850.21, 2506518.52)
SI_2.5 <- c(0.89, 0.85, 2.73, 58.65, 844.61)

df_SI <- tibble(m, SI_0.5, SI_1, SI_2.5)
colnames(df_SI)[c(2:4)] = c("lambda = 0.5", "lambda = 1", "lambda = 2.5")
df_SI

dfSurprise <- df_SI %>% pivot_longer(cols = starts_with("lambda ="), names_to = "lambda")

zPoisPlot <- ggplot(dfSurprise, aes(x = m, y = value, col=lambda, group=lambda)) + 
  geom_line() + 
  geom_point(aes(shape=lambda, col=lambda)) +
  scale_y_continuous(trans = 'log10', labels = scales::comma) + scale_x_continuous(limits = c(0.5, 10.5)) + 
  ylab("log(SI)") + 
  theme(legend.title = element_blank())
#+ ggtitle("Surprise index values for zero-truncated Poisson distribution") + theme(plot.title = element_text(hjust = 0.5))
  
zPoisPlot
```


```{r}
### Geometric distribution
n <- 10
m <- c(1, 5, 10, 20, 50)
SI_0.01 <- c(0.51, 0.53, 0.56, 0.62, 0.84)
SI_0.25 <- c(1.02, 3.21, 13.53, 240.26, 1345356.92)
SI_0.8 <- c(20.83, 13020.83, 40690104.16, 3.97*10^(14), 3.70*10^(35))

df_SI <- tibble(m, SI_0.01, SI_0.25, SI_0.8)
colnames(df_SI)[c(2:4)] = c("p = 0.01", "p = 0.25", "p = 0.8")
df_SI

dfSurprise <- df_SI %>% pivot_longer(cols = starts_with("p ="), names_to = "prob")

geomPlot <- ggplot(dfSurprise, aes(x = m, y = value, col=prob, group=prob)) + 
  geom_line() + 
  geom_point(aes(shape=prob, col=prob)) +
  scale_y_continuous(trans = 'log10', labels=trans_format('log10',math_format(10^.x))) + scale_x_continuous(limits = c(0.5, 50.5)) + 
  ylab("log(SI)") + 
  theme(legend.title = element_blank()) 
#+ ggtitle("Surprise index values for geometric distribution") + theme(plot.title = element_text(hjust = 0.5))
  
geomPlot
```












